### PR TITLE
Lobby2

### PR DESCRIPTION
**Pull request by kesang20**
rebasing commit

### CODE REVIEW

**Review by heemo521 — APPROVED** [review]

**Review by carolinepeake — COMMENTED** [review]
Sorry I didn't realize I only viewed the first set of commits, will update comment once finished looking at second set, which I'm doing rn.

**Review by carolinepeake — COMMENTED** [review]
This looks great!  A couple notes:
1) Do we want to add isLoggedIn to the redux store?  
2) May want to refactor some of the application-wide CSS (e.g., font, colorscheme) into a theme if we have time post Wed.

3)Re CreateGame.js: The createMatch method returns an object with matchID as the only property.  (also the min # of players is 3) And the joinMatch method will return an object the credential auth the client will need to use in future game plays and a playerID for the client.  Oh, so we'll probably want to keep the auth token in the redux store as well and maybe use the dispatch function in the .then called after the joinMatch method to set the playerID and credential/auth state in the redux store.   

4) re Lobby.js:  line 51-- if we don't specify a playerID, boardgame.io will assign the seq. next playerID, and return it to us along with the client's auth token, which we can prolly dispatch to the redux store once they are returned.

But looks awesome - you're blazing through!

**Comment by heemo521** [comment]
> This looks great! A couple notes:
> 
> 1. Do we want to add isLoggedIn to the redux store?
> 2. May want to refactor some of the application-wide CSS (e.g., font, colorscheme) into a theme if we have time post Wed.
> 
> 3)Re CreateGame.js: The createMatch method returns an object with matchID as the only property. (also the min # of players is 3) And the joinMatch method will return an object the credential auth the client will need to use in future game plays and a playerID for the client. Oh, so we'll probably want to keep the auth token in the redux store as well and maybe use the dispatch function in the .then called after the joinMatch method to set the playerID and credential/auth state in the redux store.
> 
> 4. re Lobby.js:  line 51-- if we don't specify a playerID, boardgame.io will assign the seq. next playerID, and return it to us along with the client's auth token, which we can prolly dispatch to the redux store once they are returned.
> 
> But looks awesome - you're blazing through!

I agree. Any user story data should be stored in the global state as we'll need it throughout the app. Token, credential, userid, username, etc. should be stored in the global store. I'll refactor by today but we should have working game by today.

**Review by crypto-bender — APPROVED** [review]
Good to pull? Looks A1 to me.

**Pull request merged**
